server:
  port: 8080

spring:
  profiles:
    include: jwt
  # DB
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: username
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      platform: postgres